### ISSUE TITLE
Centralize user agent's logs in the host machine

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#74]
the dispatcher logs some errors. But they are not very helpful. Even I don't understand them.
We should log what went wrong and why.
The logs should be more verbose and differentiated

**Comment by cz8s** [comment]
eg. if we get errors from docker we should pass the errormessage on to the logs and the requesting instance

**Comment by jeffersonhsta** [comment]
@cz8s just for little more clarification on this issue. You want to be able to see all logs from the Docker or just errors?

If is just errors it is possible the docker identify what is error?
Because I don't know if there is a layer on Pixelated to print the stack trace on the log and report nothing to the container.

I am thinking that you want exactly what the command "docker log <container_id>" does.

**Comment by cz8s** [comment]
For starters it would be nice to get the logs from docker to the logs from the dispatcher.
Since this is a feature for admins, it doesn't have to be shown in the browser.
In the long run, the dispatcher just has to be more verbose what caused an error.
I sometimes get a error 500 in the logs. And don't even know to which service the dispatcher was talking to when it got that error.

**Comment by fbernitt** [comment]
Currently it looks to me as the User-Agent logs to the file /tmp/pixelated.log, the /tmp folder is mounted to /tmp on the host system. What if there are two user agents running at the same time?

**Comment by rafaelzlisboa** [comment]
all agents append to this same file, and the docker container id is added
to the log's format

**Comment by rafaelzlisboa** [comment]
things we believe are missing:

- [ ] move logs from /tmp to /var/log
- [ ] add log rotation (on the dispatcher machine)

**Comment by fbernitt** [comment]
Works for me, but we should make that move away from /tmp rather sooner than later.
