### ISSUE TITLE
Improve command-line interface help

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-dispatcher#91]
## Why

Some parameters in the `pixelated-dispatcher` CLI are not very clear to newcomers and maybe could use some more detailed explanation or renaming to be more clear.

## Definition of done

When you do a `pixelated-dispatcher --help`, the operations and parameters are more descriptive and it's easier for someone not familiar with the application to understand.

**Comment by cz8s** [comment]
the dispatcher can't start the user-agent anymore because the command-line arguments for the user-agent changed. I get this error from the user-agent:

usage: pixelated-user-agent [-h] [--debug] [--dispatcher file]
                            [--dispatcher-stdin] [-c <configfile>]
                            [--home HOME] [-lc <leap-provider.crt>]
                            [-lf <leap provider certificate fingerprint>]
                            [--host HOST] [--port PORT] [-sk <server.key>]
                            [-sc <server.crt>] [--register provider username]
pixelated-user-agent: error: unrecognized arguments: --leap-cert-fingerprint 2B:06:48:20:E2:22:2E:22:AA:48:42:9B:2B:EF:AF:3E:E0:C4:DC:9E

**Comment by tiagoferraz** [comment]
Please, also see #95

**Comment by fbernitt** [comment]
What do you think about either using single character options in combination with a single '-' or multi cahracter options with '--'? And what about being explicit with option names? So instead of using -lf use --leap-fingerprint (or at least --lf)? Would really like if we could stick a little bit to the unix conventions.
